# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'FoodOnYourMind_Swift' do

use_frameworks!
	pod 'IQDropDownTextField'
	pod 'AERecord'
	pod 'PonyDebugger', '~> 0.4.3'

end

target 'FoodOnYourMind(Swift)Tests' do

end

